In [1]:
%load_ext autoreload
%autoreload 2

# `Logit` on Orders - Logistic Regression (~1h)

## Select features

🎯 Haydi `wait_time` ve `delay_vs_expected` değişkenlerinin çok `iyi/kötü review`lar üzerindeki etkisini inceleyelim.

👉 `orders` training_set’imizi kullanarak iki adet `multivariate logistic regression` çalıştıracağız:
- `logit_one` → `dim_is_one_star` tahmini için  
- `logit_five` → `dim_is_five_star` tahmini için.

In [2]:
import pandas as pd
import seaborn as sns
import statsmodels.api as sm
import statsmodels.formula.api as smf
import matplotlib.pyplot as plt

👉 Dataset’inizi import edin:

In [4]:
from olist.order import Order
orders = Order().get_training_data(with_distance_seller_customer=True)
orders

,order_id,wait_time,expected_wait_time,delay_vs_expected,order_status,dim_is_five_star,dim_is_one_star,review_score,number_of_items,number_of_sellers,price,freight_value,distance_seller_customer
0,e481f51cbdc54678b7cc49136f2d6af7,8.436574,15.544063,0.0,delivered,0,0,4,1,1,29.99,8.72,18.063837
1,53cdb2fc8bc7dce0b6741e2150273451,13.782037,19.137766,0.0,delivered,0,0,4,1,1,118.70,22.76,856.292580
2,47770eb9100c2d0c44946d9cf07ec65d,9.394213,26.639711,0.0,delivered,1,0,5,1,1,159.90,19.22,514.130333
3,949d5b44dbf5de918fe9c16f97b45f8a,13.208750,26.188819,0.0,delivered,1,0,5,1,1,45.00,27.20,1822.800366
4,ad21c59c0840e6cb83a9ceb5573f8159,2.873877,12.112049,0.0,delivered,1,0,5,1,1,19.90,8.72,30.174037
...,...,...,...,...,...,...,...,...,...,...,...,...,...
95875,9c5dedf39a927c1b2549525ed64a053c,8.218009,18.587442,0.0,delivered,1,0,5,1,1,72.00,13.08,69.481037
95876,63943bddc261676b46f01ca7ac2f7bd8,22.193727,23.459051,0.0,delivered,0,0,4,1,1,174.90,20.10,474.098245
95877,83c1379a015df1e13d02aae0204711ab,24.859421,30.384225,0.0,delivered,1,0,5,1,1,205.99,65.02,968.051192
95878,11c177c8e97725db2631073c19f07b62,17.086424,37.105243,0.0,delivered,0,0,2,2,1,359.98,81.18,370.146853
95879,66dea50a8b16d9b4dee7af250b4be1a5,7.674306,25.126736,0.0,delivered,1,0,5,1,1,68.50,18.36,631.817784

👉 Kullanmak istediğiniz feature’ları bir listede seçin:

⚠️ Data leakage yaratmadığınızdan emin olun (yani target’tan türetilmiş feature’ları seçmeyin)

💡 `wait_time` ve `delay_vs_expected` değişkenlerinin etkisini anlayabilmek için diğer feature’ların etkisini kontrol etmemiz gerekir, bu yüzden listenize ilgili olabilecek tüm feature’ları dahil edin.

In [7]:
features = ["wait_time","delay_vs_expected","price","freight_value","distance_seller_customer","number_of_items","number_of_sellers"]

🕵🏻 Feature’larınızın `multicollinearity` durumunu `VIF index` kullanarak kontrol edin.

* Çok yüksek olmamalıdır (tercihen < 10), böylece partial regression coefficient’larına ve ilgili `p-values` değerlerine güvenebiliriz.
* Verinizi standardize etmeyi unutmayın!
    * Bir `VIF Analysis`, bir feature’ın diğer feature’lara karşı regresyonunu yaparak hesaplanır...
    * Bu yüzden herhangi bir linear regression çalıştırmadan önce feature’ların `scale etkisini kaldırmak` ve eşit öneme sahip olmalarını sağlamak istersiniz!
    
    
📚 <a href="https://www.statisticshowto.com/variance-inflation-factor/">Statistics How To - Variance Inflation Factor</a>

📚  <a href="https://online.stat.psu.edu/stat462/node/180/">PennState - Detecting Multicollinearity Using Variance Inflation Factors</a>

⚖️ Standardize etme:

In [16]:
from sklearn.preprocessing import StandardScaler
X = orders[features]

scaler = StandardScaler()
X_scaled = pd.DataFrame(
    scaler.fit_transform(X),
    columns=features
)
X_scaled

,wait_time,delay_vs_expected,price,freight_value,distance_seller_customer,number_of_items,number_of_sellers
0,-0.431195,-0.161782,-0.513805,-0.652042,-0.979480,-0.264596,-0.112545
1,0.134174,-0.161782,-0.086641,0.000467,0.429745,-0.264596,-0.112545
2,-0.329909,-0.161782,0.111749,-0.164054,-0.145496,-0.264596,-0.112545
3,0.073540,-0.161782,-0.441528,0.206816,2.054632,-0.264596,-0.112545
4,-1.019540,-0.161782,-0.562391,-0.652042,-0.959120,-0.264596,-0.112545
...,...,...,...,...,...,...,...
95867,-0.454311,-0.161782,-0.311515,-0.449411,-0.893038,-0.264596,-0.112545
95868,1.023847,-0.161782,0.183978,-0.123156,-0.212798,-0.264596,-0.112545
95869,1.305787,-0.161782,0.333686,1.964500,0.617633,-0.264596,-0.112545
95870,0.483667,-0.161782,1.075192,2.715536,-0.387560,1.601614,-0.112545
95871,-0.511817,-0.161782,-0.328368,-0.204023,0.052359,-0.264596,-0.112545

👉 Olası multicollinearity durumlarını analiz etmek için VIF Analysis’inizi çalıştırın:

In [11]:
import pandas as pd
from statsmodels.stats.outliers_influence import variance_inflation_factor

vif_df = pd.DataFrame()
vif_df["feature"] = X_scaled.columns
vif_df["VIF"] = [
    variance_inflation_factor(X_scaled.values, i)
    for i in range(X_scaled.shape[1])
]

vif_df

                    feature       VIF
0                 wait_time  2.624944
1         delay_vs_expected  2.213500
2                     price  1.208582
3             freight_value  1.673727
4  distance_seller_customer  1.442040
5           number_of_items  1.371316
6         number_of_sellers  1.093349

## Logistic Regressions

👉 İki adet `Logistic Regression` modeli fit edin:
- `logit_one` → `dim_is_one_star` tahmini için
- `logit_five` → `dim_is_five_star` tahmini için.

`Logit 1️⃣`

In [18]:
import statsmodels.api as sm

X_scaled = X_scaled.reset_index(drop=True)
X = sm.add_constant(X_scaled)  # intercept ekle

y_one = orders["dim_is_one_star"]
y_one = y_one.reset_index(drop=True)

logit_one = sm.Logit(y_one, X).fit()

print(logit_one.summary())

Optimization terminated successfully.
         Current function value: 0.273582
         Iterations 7
                           Logit Regression Results
==============================================================================
Dep. Variable:        dim_is_one_star   No. Observations:                95872
Model:                          Logit   Df Residuals:                    95864
Method:                           MLE   Df Model:                            7
Date:                Mon, 23 Feb 2026   Pseudo R-squ.:                  0.1448
Time:                        20:44:55   Log-Likelihood:                -26229.
converged:                       True   LL-Null:                       -30669.
Covariance Type:            nonrobust   LLR p-value:                     0.000
============================================================================================
                               coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------------
const                       -2.4676      0.013   -190.852      0.000      -2.493      -2.442
wait_time                    0.7124      0.017     42.173      0.000       0.679       0.746
delay_vs_expected            0.2553      0.019     13.801      0.000       0.219       0.292
price                        0.0505      0.011      4.464      0.000       0.028       0.073
freight_value               -0.0219      0.013     -1.697      0.090      -0.047       0.003
distance_seller_customer    -0.1785      0.014    -12.934      0.000      -0.206      -0.151
number_of_items              0.2500      0.011     23.634      0.000       0.229       0.271
number_of_sellers            0.1778      0.008     22.642      0.000       0.162       0.193
============================================================================================

`Logit 5️⃣`

In [19]:
import statsmodels.api as sm

X_scaled = X_scaled.reset_index(drop=True)
X = sm.add_constant(X_scaled) 

y_one = orders["dim_is_five_star"]
y_one = y_one.reset_index(drop=True)

logit_one = sm.Logit(y_one, X).fit()

print(logit_one.summary())

Optimization terminated successfully.
         Current function value: 0.636830
         Iterations 7
                           Logit Regression Results
==============================================================================
Dep. Variable:       dim_is_five_star   No. Observations:                95872
Model:                          Logit   Df Residuals:                    95864
Method:                           MLE   Df Model:                            7
Date:                Mon, 23 Feb 2026   Pseudo R-squ.:                 0.05806
Time:                        20:45:10   Log-Likelihood:                -61054.
converged:                       True   LL-Null:                       -64817.
Covariance Type:            nonrobust   LLR p-value:                     0.000
============================================================================================
                               coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------------
const                        0.3388      0.007     47.340      0.000       0.325       0.353
wait_time                   -0.5219      0.012    -44.693      0.000      -0.545      -0.499
delay_vs_expected           -0.4330      0.024    -18.414      0.000      -0.479      -0.387
price                        0.0208      0.008      2.721      0.007       0.006       0.036
freight_value                0.0053      0.009      0.590      0.555      -0.012       0.023
distance_seller_customer     0.0872      0.008     10.509      0.000       0.071       0.103
number_of_items             -0.1365      0.008    -16.331      0.000      -0.153      -0.120
number_of_sellers           -0.1427      0.008    -18.219      0.000      -0.158      -0.127
============================================================================================

💡 Şimdi bu iki logistic regression’ın sonuçlarını analiz etme zamanı:

- Partial coefficient’ları kendi kelimelerinizle yorumlayın.
- `p-values` kullanarak istatistiksel anlamlılıklarını kontrol edin.
- Coefficient önemleri açısından `logit_one` ve `logit_five` arasında herhangi bir fark görüyor musunuz?

In [21]:
# Aşağıdaki cümlelerden doğru olanları aşağıdaki listeye kaydedin.

a = "delay_vs_expected influences five_star ratings even more than one_star ratings"
b = "wait_time influences five_star ratings even more than one_star"

your_answer = [a]
print(your_answer)

['delay_vs_expected influences five_star ratings even more than one_star ratings']

🧪 __Kodunu Test Et__

In [22]:
from nbresult import ChallengeResult

result = ChallengeResult('logit',
    answers = your_answer
)
result.write()
print(result.check())

============================= test session starts ==============================
platform darwin -- Python 3.12.9, pytest-8.3.4, pluggy-1.5.0 -- /Users/aybukealtuntas/.pyenv/versions/3.12.9/envs/workintech/bin/python
cachedir: .pytest_cache
rootdir: /Users/aybukealtuntas/data-logit/tests
plugins: anyio-4.8.0, typeguard-4.4.2
collecting ... collected 1 item

test_logit.py::TestLogit::test_question PASSED                           [100%]

============================== 1 passed in 0.01s ===============================


💯 You can commit your code:

git add tests/logit.pickle

git commit -m 'Completed logit step'

git push origin master

<details>
    <summary>- <i>Açıklamalar ve ileri seviye kavramlar</i> -</summary>


> _Diğer tüm şeyler sabitken, `delay factor`, 1-yıldız review alma ihtimalini etkilemesinden bile daha fazla, 5-yıldızdan mahrum kalma ihtimalini artırma eğilimindedir. Muhtemelen bunun sebebi, 1-yıldız review’ların bizzat çok kötü ürünleri hedeflemesi, kötü teslimatları değil._

❗️ Ancak tamamen titiz olmak için, **iki farklı modelin coefficient’larını karşılaştırırken daha dikkatli olmamız gerekir**, çünkü **benzer popülasyonlara dayanmayabilirler**!
    Burada 2 alt popülasyonumuz var: (1-yıldız verenler ve 5-yıldız verenler) ve bunlar doğaları gereği farklı davranış kalıpları sergileyebilirler. 5-yıldız vermeye daha meyilli “mutlu insanlar”ın, “gecikme” veya “fiyat” söz konusu olduğunda, 1-yıldızı “Lucky-Luke gibi ateşleyen” “huysuz insanlara” göre daha az hassas olmaları gayet mümkün...

</details>

🏁 Tebrikler!

💾 `logit.ipynb` notebook’unuzu commit ve push etmeyi unutmayın!